version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    container_name: wallet-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
