spring:
  datasource:
    url: jdbc:h2:mem:walletdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
